export const LOAD_PROJECTS_START = 'LOAD_PROJECTS_START'
export const LOAD_PROJECTS_SUCCESS = 'LOAD_PROJECTS_SUCCESS'
export const LOAD_PROJECTS_ERROR = 'LOAD_PROJECTS_ERROR'

export const LOAD_SPRINTS_START = 'LOAD_SPRINTS_START'
export const LOAD_SPRINTS_SUCCESS = 'LOAD_SPRINTS_SUCCESS'
export const LOAD_SPRINTS_ERROR = 'LOAD_SPRINTS_ERROR'
