export const LOAD_PROJECTS_START = 'LOAD_PROJECTS_START'
export const LOAD_PROJECTS_SUCCESS = 'LOAD_PROJECTS_SUCCESS'
export const LOAD_PROJECTS_ERROR = 'LOAD_PROJECTS_ERROR'

export const LOAD_SPRINTS_START = 'LOAD_SPRINTS_START'
export const LOAD_SPRINTS_SUCCESS = 'LOAD_SPRINTS_SUCCESS'
export const LOAD_SPRINTS_ERROR = 'LOAD_SPRINTS_ERROR'

export const LOAD_TICKETS_START = 'LOAD_TICKETS_START'
export const LOAD_TICKETS_SUCCESS = 'LOAD_TICKETS_SUCCESS'
export const CHANGE_TICKET = 'CHANGE_TICKET'

export const LOAD_CONTRACTS_START = 'LOAD_CONTRACT_START'
export const LOAD_CONTRACTS_SUCCESS = 'LOAD_CONTRACT_SUCCESS'
export const LOAD_CONTRACTS_ERROR = 'LOAD_CONTRACT_ERROR'

export const LOAD_USERS_START = 'LOAD_USERS_START'
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS'
export const LOAD_USERS_ERROR = 'LOAD_USERS_ERROR'
